name: 'Terraform CI/CD for EKS'

# Controls when the workflow will run
on:
  # Trigger on push to main (for apply)
  push:
    branches:
      - develop
    paths:
      - 'aws_eks/**'
      - '.github/workflows/**'
      - 'artifact/**'

  # Trigger on pull request to main (for plan)
  pull_request:
    branches:
      - develop
    paths:
      - 'aws_eks/**'
      - '.github/workflows/**'
      - 'artifact/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to "true" to destroy infrastructure. Any other value will be ignored.'
        required: true
        default: 'false'
        type: string

  # New: Schedule for automatic cleanup check
  schedule:
    # Runs every 15 minutes. You can adjust the cron expression as needed.
    # Note: Scheduled workflows can be delayed by a few minutes.
    - cron: '*/15 * * * *'

# Permissions needed for OIDC authentication and posting PR comments
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  # This job runs only on Pull Requests to generate a plan
  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        shell: bash
        working-directory: ./aws_eks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Rover from tarball
        run: |
          tar -xzf artifact/rover_linux_amd64.tar.gz -C artifact
          chmod +x artifact/rover
          sudo mv artifact/rover /usr/local/bin/
          rover --version
        working-directory: ./artifact
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
        shell: bash

      - name: Verify Rover installation
        run: rover --version

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=tfplan

      # New Step: Generate Rover image from the plan file
      - name: Generate Rover Image
        id: rover_image
        run: rover plan -plan-path tfplan --output-format png --output-path plan.png

      - name: Create Plan Text Output
        id: plan-output
        run: |
          PLAN_CONTENT=$(terraform show -no-color tfplan)
          # This is a trick to make multiline strings available to other steps
          echo "plan_text<<EOF" >> $GITHUB_ENV
          echo "$PLAN_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Modified Step: The script now includes the hosted image URL
      - name: Update PR with Plan and Image
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan & Visualization 🖼️
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*
            
            ![Terraform Plan](${{ steps.upload_image.outputs.url }})
            
            <br>
            
            <details><summary>Show Plan Text</summary>
            
            \`\`\`terraform
            ${{ env.plan_text }}
            \`\`\`
            </details>
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })