name: 'Terraform CI/CD for EKS'

# Controls when the workflow will run
on:
  # Trigger on push to main (for apply)
  push:
    branches:
      - main
    paths:
      - 'aws_eks/**'
      - '.github/workflows/**'

  # Trigger on pull request to main (for plan)
  pull_request:
    branches:
      - main
    paths:
      - 'aws_eks/**'
      - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to "true" to destroy infrastructure. Any other value will be ignored.'
        required: true
        default: 'false'
        type: string

  # New: Schedule for automatic cleanup check
  schedule:
    # Runs every 15 minutes. You can adjust the cron expression as needed.
    # Note: Scheduled workflows can be delayed by a few minutes.
    - cron: '*/15 * * * *'

# Permissions needed for OIDC authentication and posting PR comments
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  # This job runs only on Pull Requests to generate a plan
  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        shell: bash
        working-directory: ./aws_eks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
        shell: bash

      - name: Verify Rover installation
        run: rover --version

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=tfplan

      # New Step: Generate Rover image from the plan file
      - name: Generate Rover Image
        id: rover_image
        run: |
          rover -plan-path tfplan --output-format png --output-path plan.png
          echo "image_path=plan.png" >> $GITHUB_OUTPUT

      # New Step: Upload the generated image to a hosting service (imgbb)
      - name: Upload Rover Image
        id: upload_image
        uses: ivanklee/imgbb-action@v1.0.0
        with:
          path: ${{ steps.rover_image.outputs.image_path }}
          apiKey: ${{ secrets.IMGBB_API_KEY }}

      - name: Create Plan Text Output
        id: plan-output
        run: |
          PLAN_CONTENT=$(terraform show -no-color tfplan)
          # This is a trick to make multiline strings available to other steps
          echo "plan_text<<EOF" >> $GITHUB_ENV
          echo "$PLAN_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Modified Step: The script now includes the hosted image URL
      - name: Update PR with Plan and Image
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan & Visualization 🖼️
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*
            
            ![Terraform Plan](${{ steps.upload_image.outputs.url }})
            
            <br>
            
            <details><summary>Show Plan Text</summary>
            
            \`\`\`terraform
            ${{ env.plan_text }}
            \`\`\`
            </details>
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  # This job runs only on a push to the main branch to apply the changes
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        shell: bash
        working-directory: ./aws_eks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

  # New Job: Checks for inactivity and triggers destroy
  cleanup_check:
    name: 'Cleanup Check'
    runs-on: ubuntu-latest
    # This job only runs when triggered by the schedule
    if: github.event_name == 'schedule'
    permissions:
      # Required to dispatch another workflow (terraform_destroy)
      actions: write
      # Required to read repository information (workflow runs)
      contents: read

    steps:
      - name: Get last successful apply run and trigger destroy if inactive
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflowName = 'Terraform CI/CD for EKS';
            const branch = 'main';
            const event = 'push';
            const status = 'success';
            const inactivityThresholdMinutes = 15;
            // IMPORTANT: This must match your actual workflow filename.
            const workflowFileName = 'worflow.yml';

            // Find the last successful 'apply' run
            const { data: runs } = await github.rest.actions.listWorkflowRunsForRepo({
              owner,
              repo,
              workflow_id: workflowName,
              branch,
              event,
              status,
              per_page: 1
            });

            if (runs.workflow_runs.length === 0) {
              console.log('No successful apply runs found on main branch. No destroy triggered.');
              return;
            }

            const lastRunTime = new Date(runs.workflow_runs[0].updated_at);
            const currentTime = new Date();
            const diffMinutes = (currentTime - lastRunTime) / (1000 * 60);

            console.log(`Last successful apply was ${diffMinutes.toFixed(2)} minutes ago.`);

            if (diffMinutes >= inactivityThresholdMinutes) {
              console.log(`Inactivity threshold of ${inactivityThresholdMinutes} minutes met. Triggering destroy.`);
              // Trigger the destroy job by dispatching this same workflow
              await github.rest.actions.createWorkflowDispatch({
                owner,
                repo,
                workflow_id: workflowFileName,
                ref: branch,
                inputs: {
                  destroy: 'true'
                }
              });
              console.log('Destroy workflow dispatched successfully.');
            } else {
              console.log('Environment is active. No destroy needed.');
            }

  # This job runs ONLY when manually triggered with the correct input
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    # This condition ensures the job only runs when manually dispatched with destroy=true
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'
    defaults:
      run:
        shell: bash
        working-directory: ./aws_eks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false